
  
  #    /vstudios
  #     - ./backend/app/models://mod
      - /tmp:
    depends_on:
      -
      - ra
      - "
  rabb
    image: rabbitmq:3-management
    ports
      - "5672:5672"
      - "15672:15672"
 
