
  
  #    /vstudios
  #     - ./backend/app/models://mod
      - /tmp:
    depends_on:
      -
      - rabbiredis:
      - "6379:6379"
  rabbi
    image: rabbitmq:3-management
    ports
      - "5672:5672"
      - "15672:15672"
 
