services:

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/app:/app
  #     - ./backend/app/voice-studios-uploads:/app/voice-studios-uploads
  #     - ./backend/app/models:/app/models
 QUEUE ----------------- #
  celery_worker:
    build:
      context: ./backend
    command: celery -A voice_studio_stack.task_queue.celery_q.tasks.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - backend/app/.env
    volumes:
      - ./backend/app:/app
      - /tmp:/tmp
    depends_on:
      - redis
      - rabbitmq
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
 
