services:
  # ----------------- APP ----------------- #
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/app:/app
  #     - ./backend/app/avatar-studio-uploads:/app/avatar-studio-uploads
  #     - /tmp:/tmp
  #   env_file:
  #     - ./backend/app/.env
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #     - redis
  #   ports:
  #     - "8000:8000"

  # ----------------- DATABASES ----------------- #
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: omni_avatar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin 
 
  
# ----------------- VOLUMES ----------------- #
volumes:
  postgres_data:
  pgadmin-data: