
  
  #    /vstudios-u
  #     - ./backend/app/models://mod
      - /tmp:/tmp
    depends_on:
      - \
      - rabbiredis:
    image: redis:alpine
   
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
 
