
  
  #    /vstudios-uploads:/app/voiceds
  #     - ./backend/app/models:/app/mod
      - /tmp:/tmp
    depends_on:
      - redis
      - rabbitmq
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
 
